#!/bin/bash
#tag=$(wget -qO- -t1 -T2 "https://api.github.com/repos/ophub/amlogic-s9xxx-armbian/releases/latest" | grep "tag_name" | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/,//g;s/ //g')
#file=$(wget -qO- -t1 -T2 "https://api.github.com/repos/ophub/amlogic-s9xxx-armbian/releases/latest" | grep "trunk" | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/,//g;s/ //g')

#wget https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/${tag}/${file}
wget https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_noble_save_2024.04/Armbian_24.5.0-trunk_6.6.28.img.gz
gunzip Armbian_*.gz
mv Armbian_*.img armbian.img
