#==========================================================================
# Description: 手动生成和上传 boot.img 和多个 rootfs 镜像
#==========================================================================
name: UFI Armbian Build
on:
  workflow_dispatch: # 手动触发
    inputs:
      armbian_board:
        description: "选择设备板"
        required: true
        default: "ufi003"
        type: choice
        options:
          - ufi001c
          - ufi003

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 安装必要的依赖
      - name: 安装依赖
        run: |
          sudo apt update -y
          sudo apt-get install -y xz-utils zip flex bison libncurses-dev gawk libiberty-dev autoconf kmod bc build-essential gcc libc6 curl libstdc++6 git wget libssl-dev cpio p7zip-full qemu-user-static netplan.io
          sudo apt clean

      # 2. 创建工作目录并下载 boot.img
      - name: 下载 boot.img
        run: |
          mkdir -p UFI001C-Armbian
          cd UFI001C-Armbian
          wget https://github.com/YANXIAOXIH/UFI001C-Armbian/releases/download/Armbian_UFI_save_2024.04/boot.img

      # 3. 下载多个 rootfs 镜像
      - name: 下载 rootfs 镜像
        run: |
          cd UFI001C-Armbian
          wget https://github.com/YANXIAOXIH/UFI001C-Armbian/releases/download/Armbian_UFI_save_2024.04/rootfs-bookworm.img
          wget https://github.com/YANXIAOXIH/UFI001C-Armbian/releases/download/Armbian_UFI_save_2024.04/rootfs-jammy.img
          wget https://github.com/YANXIAOXIH/UFI001C-Armbian/releases/download/Armbian_UFI_save_2024.04/rootfs-noble.img

      # 4. 打包所有版本的 rootfs 镜像
      - name: 打包 Armbian 镜像
        id: repack
        run: |
          cd UFI001C-Armbian
          
          # 创建临时目录
          sudo mkdir -p temp

          # 打包 bookworm 版本
          sudo dd if=/dev/zero of=armbian-bookworm.img bs=1M count=3000
          sudo mkfs.btrfs armbian-bookworm.img
          sudo mount -o compress=zstd:15 armbian-bookworm.img temp
          sudo cp rootfs-bookworm.img temp/
          sudo cp boot.img temp/
          sudo umount temp
          sudo xz armbian-bookworm.img

          # 打包 jammy 版本
          sudo dd if=/dev/zero of=armbian-jammy.img bs=1M count=3000
          sudo mkfs.btrfs armbian-jammy.img
          sudo mount -o compress=zstd:15 armbian-jammy.img temp
          sudo cp rootfs-jammy.img temp/
          sudo cp boot.img temp/
          sudo umount temp
          sudo xz armbian-jammy.img

          # 打包 noble 版本
          sudo dd if=/dev/zero of=armbian-noble.img bs=1M count=3000
          sudo mkfs.btrfs armbian-noble.img
          sudo mount -o compress=zstd:15 armbian-noble.img temp
          sudo cp rootfs-noble.img temp/
          sudo cp boot.img temp/
          sudo umount temp
          sudo xz armbian-noble.img

          echo "build_tag=Armbian_${{ inputs.armbian_board }}_$(date +"%Y.%m")" >> ${GITHUB_OUTPUT}

      # 5. 上传所有版本的镜像到 GitHub Release
      - name: 上传 Armbian 镜像至 Release
        uses: ncipollo/release-action@main
        with:
          artifacts: |
            UFI001C-Armbian/armbian-bookworm.img.xz
            UFI001C-Armbian/armbian-jammy.img.xz
            UFI001C-Armbian/armbian-noble.img.xz
            UFI001C-Armbian/boot.img
          name: ${{ steps.repack.outputs.build_tag }}
          tag: ${{ steps.repack.outputs.build_tag }}
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ### 以下是 Armbian OS 镜像
            - 固件基带：${{ inputs.armbian_board }}
            - 系统信息：
              - 默认用户名：root
              - 默认密码：1234
              - 全局配置命令：armbian-config
              - WiFi名称：4G-UFI
              - WiFi密码：12345678
            - 包含以下版本：
              - rootfs-bookworm.img.xz
              - rootfs-jammy.img.xz
              - rootfs-noble.img.xz
            - 通用启动镜像：boot.img

